'use strict';

const fs = require('fs');
const path = require('path');
const { runCommand } = require('../utils/shell');
const config = require('../config/env');

const GENERATED_DOCKERFILE_MARKER = '# Generated by ReHoster';

const DEFAULT_DOCKERIGNORE = `node_modules
.git
.env
.env.*
.DS_Store
npm-debug.log
`;

function resolveDockerCommand() {
  const envOverride = process.env.DOCKER_CMD && process.env.DOCKER_CMD.trim();
  if (envOverride) {
    if (!path.isAbsolute(envOverride) || fs.existsSync(envOverride)) {
      return envOverride;
    }
  }

  const candidates = process.platform === 'win32'
    ? [
        'C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.exe',
        'C:\\Program Files\\Docker\\Docker\\resources\\docker.exe',
      ]
    : [
        '/usr/bin/docker',
        '/usr/local/bin/docker',
      ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  return 'docker';
}

const DOCKER_CMD = resolveDockerCommand();

function getDockerCommandInfo() {
  const isAbsolute = path.isAbsolute(DOCKER_CMD);
  return {
    command: DOCKER_CMD,
    isAbsolute,
    existsOnDisk: isAbsolute ? fs.existsSync(DOCKER_CMD) : null,
    envOverride: process.env.DOCKER_CMD || null,
  };
}

function normalizeDockerFailure(output) {
  const text = (output || '').toLowerCase();

  if (text.includes('enoent') || text.includes('not recognized') || text.includes('not found')) {
    return {
      status: 'cli_not_found',
      message: 'Docker CLI was not found in this runtime environment.',
    };
  }

  if (text.includes('error during connect') || text.includes('docker desktop is not running') || text.includes('cannot connect to the docker daemon') || text.includes('open //./pipe/docker_engine')) {
    return {
      status: 'daemon_unreachable',
      message: 'Docker CLI is present but the Docker daemon is not reachable. Start Docker Desktop (or the Docker service) and retry.',
    };
  }

  if (text.includes('access is denied') || text.includes('permission denied')) {
    return {
      status: 'permission_denied',
      message: 'Docker is installed, but access to the daemon was denied.',
    };
  }

  return {
    status: 'unknown',
    message: 'Docker check failed for an unknown reason.',
  };
}

async function getDockerAvailabilityDetails() {
  const cmdInfo = getDockerCommandInfo();

  if (cmdInfo.isAbsolute && cmdInfo.existsOnDisk === false) {
    return {
      available: false,
      status: 'cli_not_found',
      message: `Configured Docker command path does not exist: ${cmdInfo.command}`,
      commandInfo: cmdInfo,
      diagnostics: '',
    };
  }

  const result = await runCommand(DOCKER_CMD, ['info'], { timeout: 10000 });
  if (result.exitCode === 0) {
    return {
      available: true,
      status: 'ok',
      message: 'Docker daemon is reachable.',
      commandInfo: cmdInfo,
      diagnostics: '',
    };
  }

  const diagnostics = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
  const normalized = normalizeDockerFailure(diagnostics);
  return {
    available: false,
    status: normalized.status,
    message: normalized.message,
    commandInfo: cmdInfo,
    diagnostics,
  };
}

function getInstallCommand(appPath) {
  return fs.existsSync(path.join(appPath, 'package-lock.json')) ? 'npm ci' : 'npm install';
}

function buildNodeDockerfile({ installCommand, buildCommand, startCommand, containerPort }) {
  const dockerBuildCommand = buildCommand && buildCommand.trim().length > 0
    ? `RUN sh -lc ${JSON.stringify(buildCommand)}`
    : '';

  return `${GENERATED_DOCKERFILE_MARKER}
FROM node:20-alpine AS builder
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN ${installCommand}
COPY --chown=node:node . .
${dockerBuildCommand}

FROM node:20-alpine AS production
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN ${installCommand} --omit=dev
COPY --chown=node:node --from=builder /app .
ENV NODE_ENV=production
ENV PORT=${containerPort}
EXPOSE ${containerPort}
USER node
CMD ["sh", "-lc", ${JSON.stringify(startCommand)}]
`;
}

function buildStaticDockerfile({ installCommand, buildCommand, containerPort }) {
  const dockerBuildCommand = buildCommand && buildCommand.trim().length > 0
    ? buildCommand
    : 'npm run build';

  return `${GENERATED_DOCKERFILE_MARKER}
FROM node:20-alpine AS builder
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN ${installCommand}
COPY --chown=node:node . .
RUN sh -lc ${JSON.stringify(dockerBuildCommand)}
RUN mkdir -p /site && \
  if [ -d dist ]; then cp -R dist/. /site/; \
  elif [ -d build ]; then cp -R build/. /site/; \
  elif [ -d public ]; then cp -R public/. /site/; \
  else echo "No static build output found (expected dist, build, or public)." >&2; exit 1; fi

FROM nginx:alpine
COPY --from=builder /site /usr/share/nginx/html
RUN chmod -R a+rX /usr/share/nginx/html
RUN find /etc/nginx -name 'default.conf' -delete 2>/dev/null || true; CONF_DIR=$(if [ -d /etc/nginx/http.d ]; then echo /etc/nginx/http.d; else echo /etc/nginx/conf.d; fi); printf '%s\\n' 'server {' '  listen ${containerPort};' '  server_name _;' '  root /usr/share/nginx/html;' '  index index.html;' '' '  location / {' '    try_files $uri $uri/ /index.html;' '  }' '}' > "$CONF_DIR/default.conf"
EXPOSE ${containerPort}
CMD ["nginx", "-g", "daemon off;"]
`;
}

function buildPureStaticDockerfile({ buildCommand, containerPort }) {
  // Used when no package.json is present — no Node/npm steps
  const hasBuild = buildCommand && buildCommand.trim().length > 0;

  if (!hasBuild) {
    return `${GENERATED_DOCKERFILE_MARKER}
FROM nginx:alpine
COPY . /usr/share/nginx/html
RUN chmod -R a+rX /usr/share/nginx/html
RUN find /etc/nginx -name 'default.conf' -delete 2>/dev/null || true; CONF_DIR=$(if [ -d /etc/nginx/http.d ]; then echo /etc/nginx/http.d; else echo /etc/nginx/conf.d; fi); printf '%s\\n' 'server {' '  listen ${containerPort};' '  server_name _;' '  root /usr/share/nginx/html;' '  index index.html;' '' '  location / {' '    try_files $uri $uri/ /index.html;' '  }' '}' > "$CONF_DIR/default.conf"
EXPOSE ${containerPort}
CMD ["nginx", "-g", "daemon off;"]
`;
  }

  return `${GENERATED_DOCKERFILE_MARKER}
FROM alpine AS builder
WORKDIR /app
COPY . .
RUN sh -lc ${JSON.stringify(buildCommand)}
RUN mkdir -p /site && \\
  if [ -d dist ]; then cp -R dist/. /site/; \\
  elif [ -d build ]; then cp -R build/. /site/; \\
  elif [ -d out ]; then cp -R out/. /site/; \\
  elif [ -d public ]; then cp -R public/. /site/; \\
  else cp -R . /site/; fi

FROM nginx:alpine
COPY --from=builder /site /usr/share/nginx/html
RUN chmod -R a+rX /usr/share/nginx/html
RUN find /etc/nginx -name 'default.conf' -delete 2>/dev/null || true; CONF_DIR=$(if [ -d /etc/nginx/http.d ]; then echo /etc/nginx/http.d; else echo /etc/nginx/conf.d; fi); printf '%s\\n' 'server {' '  listen ${containerPort};' '  server_name _;' '  root /usr/share/nginx/html;' '  index index.html;' '' '  location / {' '    try_files $uri $uri/ /index.html;' '  }' '}' > "$CONF_DIR/default.conf"
EXPOSE ${containerPort}
CMD ["nginx", "-g", "daemon off;"]
`;
}

function shouldUseStaticContainer(serviceType, frameworks) {
  if (serviceType === 'static') return true;
  if (serviceType === 'node') return false;

  const frameworkKeys = new Set((frameworks || []).map((framework) => framework.key));
  if (frameworkKeys.has('next') || frameworkKeys.has('nuxt') || frameworkKeys.has('remix') || frameworkKeys.has('express') || frameworkKeys.has('fastify')) {
    return false;
  }

  return frameworkKeys.has('vite')
    || frameworkKeys.has('react')
    || frameworkKeys.has('vue')
    || frameworkKeys.has('angular')
    || frameworkKeys.has('svelte')
    || frameworkKeys.has('static');
}

function isLegacyGeneratedDockerfile(content) {
  return content.includes('RUN npm run build || true')
    || content.includes('COPY --chown=node:node --from=builder /app .')
    || content.includes("RUN printf 'server {")
    || content === buildStaticDockerfile({ installCommand: 'npm install', buildCommand: '', containerPort: 80 }).replace(`${GENERATED_DOCKERFILE_MARKER}\n`, '');
}

async function isDockerAvailable() {
  const details = await getDockerAvailabilityDetails();
  return details.available;
}

async function buildImage(appPath, imageName) {
  const result = await runCommand(DOCKER_CMD, ['build', '-t', imageName, appPath], {
    cwd: appPath,
    timeout: 10 * 60 * 1000,
  });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`Docker build failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function runContainer({ imageName, containerName, hostPort, containerPort, envVars, restartPolicy, cpuLimit, memoryLimit }) {
  const args = ['run', '-d', '--name', containerName, '-p', `${hostPort}:${containerPort}`];

  if (restartPolicy) {
    args.push('--restart', restartPolicy);
  }

  if (cpuLimit) {
    args.push('--cpus', String(cpuLimit));
  }

  if (memoryLimit) {
    args.push('--memory', String(memoryLimit));
  }

  if (envVars && typeof envVars === 'object') {
    for (const [key, val] of Object.entries(envVars)) {
      args.push('-e', `${key}=${val}`);
    }
  }

  args.push(imageName);

  const result = await runCommand(DOCKER_CMD, args, { timeout: 30000 });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`docker run failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function stopContainer(containerName) {
  return runCommand(DOCKER_CMD, ['stop', containerName], { timeout: 30000 });
}

async function startContainer(containerName) {
  const result = await runCommand(DOCKER_CMD, ['start', containerName], { timeout: 30000 });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`docker start failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function restartContainer(containerName) {
  const result = await runCommand(DOCKER_CMD, ['restart', containerName], { timeout: 30000 });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`docker restart failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function removeContainer(containerName) {
  return runCommand(DOCKER_CMD, ['rm', '-f', containerName], { timeout: 30000 });
}

async function getLogs(containerName, lines = 100) {
  const result = await runCommand(DOCKER_CMD, ['logs', '--tail', String(lines), containerName], {
    timeout: 15000,
  });
  return result.stdout + result.stderr;
}

async function inspect(containerName) {
  const result = await runCommand(DOCKER_CMD, ['inspect', containerName], { timeout: 10000 });
  if (result.exitCode !== 0) return null;
  try {
    const parsed = JSON.parse(result.stdout);
    return Array.isArray(parsed) ? parsed[0] : parsed;
  } catch {
    return null;
  }
}

async function getContainerStatus(containerName) {
  const data = await inspect(containerName);
  if (!data) return 'not_found';
  const state = data.State && data.State.Status;
  if (state === 'running') return 'running';
  if (state === 'exited') return 'stopped';
  return state || 'unknown';
}

async function generateDockerfile(appPath, serviceType, detectedFrameworks, buildCommand, startCommand, containerPort) {
  const dockerfilePath = path.join(appPath, 'Dockerfile');
  const dockerignorePath = path.join(appPath, '.dockerignore');

  if (!fs.existsSync(dockerignorePath)) {
    fs.writeFileSync(dockerignorePath, DEFAULT_DOCKERIGNORE, 'utf8');
  }

  let frameworks = [];
  try {
    if (detectedFrameworks) {
      frameworks = typeof detectedFrameworks === 'string'
        ? JSON.parse(detectedFrameworks)
        : detectedFrameworks;
    }
  } catch {}

  const hasPackageJson = fs.existsSync(path.join(appPath, 'package.json'));
  const installCommand = getInstallCommand(appPath);
  const resolvedContainerPort = containerPort || config.defaultContainerPort;
  const isStatic = shouldUseStaticContainer(serviceType, frameworks);

  if (!hasPackageJson && !isStatic) {
    throw new Error(
      'No package.json found in this repository. ReHoster requires a package.json to build Node.js apps. ' +
      'Add a package.json, or change the service type to "static" if this is a plain static site.'
    );
  }

  // For static apps without package.json, avoid all npm steps.
  // Only pass the build command through if the user explicitly set something non-npm.
  const isNpmDefaultCmd = (cmd) => !cmd || /^\s*(npm (install|ci|run build)|yarn( build)?)\s*/.test(cmd);
  const resolvedBuildCommand = buildCommand && buildCommand.trim().length > 0
    ? buildCommand
    : (isStatic && hasPackageJson ? 'npm run build' : null);
  const resolvedStartCommand = startCommand && startCommand.trim().length > 0
    ? startCommand
    : 'npm start';

  const content = (!hasPackageJson && isStatic)
    ? buildPureStaticDockerfile({
        buildCommand: isNpmDefaultCmd(resolvedBuildCommand) ? null : resolvedBuildCommand,
        containerPort: resolvedContainerPort,
      })
    : isStatic
      ? buildStaticDockerfile({ installCommand, buildCommand: resolvedBuildCommand, containerPort: resolvedContainerPort })
      : buildNodeDockerfile({
          installCommand,
          buildCommand: resolvedBuildCommand,
          startCommand: resolvedStartCommand,
          containerPort: resolvedContainerPort,
        });

  let shouldWrite = !fs.existsSync(dockerfilePath);
  if (!shouldWrite) {
    const existing = fs.readFileSync(dockerfilePath, 'utf8');
    shouldWrite = existing.includes(GENERATED_DOCKERFILE_MARKER) || isLegacyGeneratedDockerfile(existing);
  }

  if (shouldWrite) {
    fs.writeFileSync(dockerfilePath, content, 'utf8');
  }
}

async function removeImage(imageName) {
  return runCommand(DOCKER_CMD, ['rmi', '-f', imageName], { timeout: 30000 });
}

module.exports = {
  isDockerAvailable,
  getDockerAvailabilityDetails,
  getDockerCommandInfo,
  buildImage,
  runContainer,
  stopContainer,
  startContainer,
  restartContainer,
  removeContainer,
  getLogs,
  inspect,
  getContainerStatus,
  generateDockerfile,
  removeImage,
};
