'use strict';

const fs = require('fs');
const path = require('path');
const { runCommand } = require('../utils/shell');
const config = require('../config/env');

const GENERATED_DOCKERFILE_MARKER = '# Generated by ReHoster';

const DEFAULT_DOCKERIGNORE = `node_modules
.git
.env
.env.*
.DS_Store
npm-debug.log
`;

function getPrereqInstallerPath() {
  const repoRoot = path.resolve(__dirname, '..', '..');
  return process.platform === 'win32'
    ? path.join(repoRoot, 'install-prereqs.ps1')
    : path.join(repoRoot, 'install-prereqs.sh');
}

function resolveDockerCommand() {
  const envOverride = process.env.DOCKER_CMD && process.env.DOCKER_CMD.trim();
  if (envOverride) {
    if (!path.isAbsolute(envOverride) || fs.existsSync(envOverride)) {
      return envOverride;
    }
  }

  const candidates = process.platform === 'win32'
    ? [
        'C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.exe',
        'C:\\Program Files\\Docker\\Docker\\resources\\docker.exe',
      ]
    : [
        '/usr/bin/docker',
        '/usr/local/bin/docker',
      ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  return 'docker';
}

const DOCKER_CMD = resolveDockerCommand();

function getDockerCommandInfo() {
  const isAbsolute = path.isAbsolute(DOCKER_CMD);
  return {
    command: DOCKER_CMD,
    isAbsolute,
    existsOnDisk: isAbsolute ? fs.existsSync(DOCKER_CMD) : null,
    envOverride: process.env.DOCKER_CMD || null,
  };
}

function analyzeDependencyManifests(appPath) {
  const hasPackageJson = fs.existsSync(path.join(appPath, 'package.json'));
  const hasPackageLock = fs.existsSync(path.join(appPath, 'package-lock.json'));
  const hasYarnLock = fs.existsSync(path.join(appPath, 'yarn.lock'));
  const hasPnpmLock = fs.existsSync(path.join(appPath, 'pnpm-lock.yaml'));
  const hasRequirementsTxt = fs.existsSync(path.join(appPath, 'requirements.txt'));
  const hasPyproject = fs.existsSync(path.join(appPath, 'pyproject.toml'));
  const hasPipfile = fs.existsSync(path.join(appPath, 'Pipfile'));

  let packageManager = null;
  if (hasPnpmLock) packageManager = 'pnpm';
  else if (hasYarnLock) packageManager = 'yarn';
  else if (hasPackageJson) packageManager = 'npm';

  return {
    hasPackageJson,
    hasPackageLock,
    hasYarnLock,
    hasPnpmLock,
    hasRequirementsTxt,
    hasPyproject,
    hasPipfile,
    packageManager,
    hasLockfile: hasPackageLock || hasYarnLock || hasPnpmLock,
    hasPythonManifest: hasRequirementsTxt || hasPyproject || hasPipfile,
  };
}

function normalizeDockerFailure(output) {
  const text = (output || '').toLowerCase();

  if (text.includes('enoent') || text.includes('not recognized') || text.includes('not found')) {
    return {
      status: 'cli_not_found',
      message: 'Docker CLI was not found in this runtime environment.',
    };
  }

  if (text.includes('error during connect') || text.includes('docker desktop is not running') || text.includes('cannot connect to the docker daemon') || text.includes('open //./pipe/docker_engine')) {
    return {
      status: 'daemon_unreachable',
      message: 'Docker CLI is present but the Docker daemon is not reachable. Start Docker Desktop (or the Docker service) and retry.',
    };
  }

  if (text.includes('access is denied') || text.includes('permission denied')) {
    return {
      status: 'permission_denied',
      message: 'Docker is installed, but access to the daemon was denied.',
    };
  }

  return {
    status: 'unknown',
    message: 'Docker check failed for an unknown reason.',
  };
}

async function getDockerAvailabilityDetails() {
  const cmdInfo = getDockerCommandInfo();

  if (cmdInfo.isAbsolute && cmdInfo.existsOnDisk === false) {
    return {
      available: false,
      status: 'cli_not_found',
      message: `Configured Docker command path does not exist: ${cmdInfo.command}`,
      commandInfo: cmdInfo,
      diagnostics: '',
    };
  }

  const result = await runCommand(DOCKER_CMD, ['info'], { timeout: 10000 });
  if (result.exitCode === 0) {
    return {
      available: true,
      status: 'ok',
      message: 'Docker daemon is reachable.',
      commandInfo: cmdInfo,
      diagnostics: '',
    };
  }

  const diagnostics = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
  const normalized = normalizeDockerFailure(diagnostics);
  return {
    available: false,
    status: normalized.status,
    message: normalized.message,
    commandInfo: cmdInfo,
    diagnostics,
  };
}

function getNodeInstallPlan(appPath) {
  const manifests = analyzeDependencyManifests(appPath);

  if (manifests.hasPnpmLock) {
    return {
      manager: 'pnpm',
      setupCommand: 'corepack enable && corepack prepare pnpm@latest --activate',
      installCommand: 'pnpm install --frozen-lockfile',
      productionInstallCommand: 'pnpm install --frozen-lockfile --prod',
    };
  }

  if (manifests.hasYarnLock) {
    return {
      manager: 'yarn',
      setupCommand: 'corepack enable && corepack prepare yarn@stable --activate',
      installCommand: 'yarn install --frozen-lockfile',
      productionInstallCommand: 'yarn install --frozen-lockfile --production=true',
    };
  }

  return {
    manager: 'npm',
    setupCommand: null,
    installCommand: manifests.hasPackageLock ? 'npm ci' : 'npm install',
    productionInstallCommand: manifests.hasPackageLock ? 'npm ci --omit=dev' : 'npm install --omit=dev',
  };
}

function getPythonDependencyInstallCommand(appPath) {
  const manifests = analyzeDependencyManifests(appPath);

  if (manifests.hasRequirementsTxt) {
    return 'if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi';
  }

  if (manifests.hasPyproject) {
    return 'if [ -f pyproject.toml ] && [ -f poetry.lock ]; then pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --only main; elif [ -f pyproject.toml ]; then pip install --no-cache-dir .; fi';
  }

  if (manifests.hasPipfile) {
    return 'if [ -f Pipfile ]; then pip install --no-cache-dir pipenv && PIPENV_VENV_IN_PROJECT=0 pipenv install --system --deploy; fi';
  }

  return null;
}

async function attemptDockerAutoRepair() {
  const installerPath = getPrereqInstallerPath();
  if (!fs.existsSync(installerPath)) {
    return { attempted: false, success: false, output: 'Prerequisite installer script not found.' };
  }

  const repoRoot = path.resolve(__dirname, '..', '..');
  const command = process.platform === 'win32' ? 'powershell.exe' : 'bash';
  const args = process.platform === 'win32'
    ? ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', installerPath]
    : [installerPath];

  const result = await runCommand(command, args, {
    cwd: repoRoot,
    timeout: 15 * 60 * 1000,
  });

  const verify = await getDockerAvailabilityDetails();
  return {
    attempted: true,
    success: verify.available,
    output: [result.stdout, result.stderr].filter(Boolean).join('\n').trim(),
    verify,
  };
}

function readPackageScripts(appPath) {
  const pkgPath = path.join(appPath, 'package.json');
  if (!fs.existsSync(pkgPath)) return {};
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    return pkg && pkg.scripts && typeof pkg.scripts === 'object' ? pkg.scripts : {};
  } catch {
    return {};
  }
}

function normalizeBuildCommandForScripts(buildCommand, hasBuildScript) {
  if (!buildCommand || buildCommand.trim().length === 0) return buildCommand;

  const cmd = buildCommand.trim().toLowerCase();
  const isDefaultLikeNodeBuild = cmd === 'npm run build'
    || cmd === 'npm install && npm run build'
    || cmd === 'npm ci && npm run build';

  if (isDefaultLikeNodeBuild && !hasBuildScript) {
    return null;
  }

  return buildCommand;
}

function buildNodeDockerfile({ setupCommand, installCommand, productionInstallCommand, pythonInstallCommand, buildCommand, startCommand, containerPort }) {
  const dockerBuildCommand = buildCommand && buildCommand.trim().length > 0
    ? `RUN sh -lc ${JSON.stringify(buildCommand)}`
    : '';

  const setupLine = setupCommand ? `RUN ${setupCommand}` : '';
  const pythonLine = pythonInstallCommand ? `RUN ${pythonInstallCommand}` : '';

  return `${GENERATED_DOCKERFILE_MARKER}
FROM node:20-alpine AS builder
WORKDIR /app
COPY --chown=node:node . .
${setupLine}
RUN ${installCommand}
${dockerBuildCommand}

FROM node:20-alpine AS production
WORKDIR /app
COPY --chown=node:node --from=builder /app .
${setupLine}
RUN ${productionInstallCommand}
RUN apk add --no-cache python3 py3-pip && ln -sf /usr/bin/python3 /usr/bin/python \
  && python3 -m venv /opt/venv \
  && chown -R node:node /opt/venv
${pythonLine}
RUN mkdir -p /app/output /app/cache && chown -R node:node /app
ENV VIRTUAL_ENV=/opt/venv
ENV PYTHONUSERBASE=/opt/venv
ENV PATH="/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV NODE_ENV=production
ENV PORT=${containerPort}
EXPOSE ${containerPort}
USER node
CMD ["sh", "-lc", ${JSON.stringify(startCommand)}]
`;
}

function buildStaticDockerfile({ setupCommand, installCommand, buildCommand, containerPort }) {
  const dockerBuildCommand = buildCommand && buildCommand.trim().length > 0
    ? buildCommand
    : 'npm run build';

  const setupLine = setupCommand ? `RUN ${setupCommand}` : '';

  return `${GENERATED_DOCKERFILE_MARKER}
FROM node:20-alpine AS builder
WORKDIR /app
COPY --chown=node:node . .
${setupLine}
RUN ${installCommand}
RUN sh -lc ${JSON.stringify(dockerBuildCommand)}
RUN mkdir -p /site && \
  if [ -d dist ]; then cp -R dist/. /site/; \
  elif [ -d build ]; then cp -R build/. /site/; \
  elif [ -d public ]; then cp -R public/. /site/; \
  else echo "No static build output found (expected dist, build, or public)." >&2; exit 1; fi

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /site /usr/share/nginx/html
RUN apk add --no-cache python3 py3-pip && ln -sf /usr/bin/python3 /usr/bin/python \
  && python3 -m venv /opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV PIP_BREAK_SYSTEM_PACKAGES=1
RUN chmod -R a+rX /usr/share/nginx/html
RUN find /etc/nginx -name 'default.conf' -delete 2>/dev/null || true; CONF_DIR=$(if [ -d /etc/nginx/http.d ]; then echo /etc/nginx/http.d; else echo /etc/nginx/conf.d; fi); printf '%s\\n' 'server {' '  listen ${containerPort};' '  server_name _;' '  root /usr/share/nginx/html;' '  index index.html;' '' '  location / {' '    try_files $uri $uri/ /index.html;' '  }' '}' > "$CONF_DIR/default.conf"
EXPOSE ${containerPort}
CMD ["nginx", "-g", "daemon off;"]
`;
}

function buildPureStaticDockerfile({ buildCommand, containerPort }) {
  // Used when no package.json is present — no Node/npm steps
  const hasBuild = buildCommand && buildCommand.trim().length > 0;

  if (!hasBuild) {
    return `${GENERATED_DOCKERFILE_MARKER}
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY . /usr/share/nginx/html
RUN apk add --no-cache python3 py3-pip && ln -sf /usr/bin/python3 /usr/bin/python \
  && python3 -m venv /opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV PIP_BREAK_SYSTEM_PACKAGES=1
RUN chmod -R a+rX /usr/share/nginx/html
RUN find /etc/nginx -name 'default.conf' -delete 2>/dev/null || true; CONF_DIR=$(if [ -d /etc/nginx/http.d ]; then echo /etc/nginx/http.d; else echo /etc/nginx/conf.d; fi); printf '%s\\n' 'server {' '  listen ${containerPort};' '  server_name _;' '  root /usr/share/nginx/html;' '  index index.html;' '' '  location / {' '    try_files $uri $uri/ /index.html;' '  }' '}' > "$CONF_DIR/default.conf"
EXPOSE ${containerPort}
CMD ["nginx", "-g", "daemon off;"]
`;
  }

  return `${GENERATED_DOCKERFILE_MARKER}
FROM alpine AS builder
WORKDIR /app
COPY . .
RUN sh -lc ${JSON.stringify(buildCommand)}
RUN mkdir -p /site && \\
  if [ -d dist ]; then cp -R dist/. /site/; \\
  elif [ -d build ]; then cp -R build/. /site/; \\
  elif [ -d out ]; then cp -R out/. /site/; \\
  elif [ -d public ]; then cp -R public/. /site/; \\
  else cp -R . /site/; fi

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /site /usr/share/nginx/html
RUN apk add --no-cache python3 py3-pip && ln -sf /usr/bin/python3 /usr/bin/python \
  && python3 -m venv /opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV PIP_BREAK_SYSTEM_PACKAGES=1
RUN chmod -R a+rX /usr/share/nginx/html
RUN find /etc/nginx -name 'default.conf' -delete 2>/dev/null || true; CONF_DIR=$(if [ -d /etc/nginx/http.d ]; then echo /etc/nginx/http.d; else echo /etc/nginx/conf.d; fi); printf '%s\\n' 'server {' '  listen ${containerPort};' '  server_name _;' '  root /usr/share/nginx/html;' '  index index.html;' '' '  location / {' '    try_files $uri $uri/ /index.html;' '  }' '}' > "$CONF_DIR/default.conf"
EXPOSE ${containerPort}
CMD ["nginx", "-g", "daemon off;"]
`;
}

function shouldUseStaticContainer(serviceType, frameworks) {
  if (serviceType === 'static') return true;
  if (serviceType === 'node') return false;

  const frameworkKeys = new Set((frameworks || []).map((framework) => framework.key));
  if (frameworkKeys.has('next') || frameworkKeys.has('nuxt') || frameworkKeys.has('remix') || frameworkKeys.has('express') || frameworkKeys.has('fastify')) {
    return false;
  }

  return frameworkKeys.has('vite')
    || frameworkKeys.has('react')
    || frameworkKeys.has('vue')
    || frameworkKeys.has('angular')
    || frameworkKeys.has('svelte')
    || frameworkKeys.has('static');
}

function isLegacyGeneratedDockerfile(content) {
  return content.includes('RUN npm run build || true')
    || content.includes('COPY --chown=node:node --from=builder /app .')
    || content.includes("RUN printf 'server {")
    || content === buildStaticDockerfile({ installCommand: 'npm install', buildCommand: '', containerPort: 80 }).replace(`${GENERATED_DOCKERFILE_MARKER}\n`, '');
}

async function isDockerAvailable() {
  const details = await getDockerAvailabilityDetails();
  return details.available;
}

async function buildImage(appPath, imageName) {
  const baseArgs = ['build', '-t', imageName, appPath];
  let result = await runCommand(DOCKER_CMD, baseArgs, {
    cwd: appPath,
    timeout: 10 * 60 * 1000,
  });

  if (result.exitCode !== 0) {
    // One fallback retry with --pull to recover from stale base image metadata.
    result = await runCommand(DOCKER_CMD, ['build', '--pull', '-t', imageName, appPath], {
      cwd: appPath,
      timeout: 12 * 60 * 1000,
    });
  }

  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`Docker build failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function runContainer({ imageName, containerName, hostPort, containerPort, envVars, restartPolicy, cpuLimit, memoryLimit }) {
  const args = ['run', '-d', '--name', containerName, '-p', `${hostPort}:${containerPort}`];

  if (restartPolicy) {
    args.push('--restart', restartPolicy);
  }

  if (cpuLimit) {
    args.push('--cpus', String(cpuLimit));
  }

  if (memoryLimit) {
    args.push('--memory', String(memoryLimit));
  }

  if (envVars && typeof envVars === 'object') {
    for (const [key, val] of Object.entries(envVars)) {
      args.push('-e', `${key}=${val}`);
    }
  }

  args.push(imageName);

  const result = await runCommand(DOCKER_CMD, args, { timeout: 30000 });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`docker run failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function stopContainer(containerName) {
  return runCommand(DOCKER_CMD, ['stop', containerName], { timeout: 30000 });
}

async function startContainer(containerName) {
  const result = await runCommand(DOCKER_CMD, ['start', containerName], { timeout: 30000 });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`docker start failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function restartContainer(containerName) {
  const result = await runCommand(DOCKER_CMD, ['restart', containerName], { timeout: 30000 });
  if (result.exitCode !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`docker restart failed:\n${output || `Exit code ${result.exitCode}`}`);
  }
  return result;
}

async function removeContainer(containerName) {
  return runCommand(DOCKER_CMD, ['rm', '-f', containerName], { timeout: 30000 });
}

async function getLogs(containerName, lines = 100) {
  const result = await runCommand(DOCKER_CMD, ['logs', '--tail', String(lines), containerName], {
    timeout: 15000,
  });
  return result.stdout + result.stderr;
}

async function inspect(containerName) {
  const result = await runCommand(DOCKER_CMD, ['inspect', containerName], { timeout: 10000 });
  if (result.exitCode !== 0) return null;
  try {
    const parsed = JSON.parse(result.stdout);
    return Array.isArray(parsed) ? parsed[0] : parsed;
  } catch {
    return null;
  }
}

async function getContainerStatus(containerName) {
  const data = await inspect(containerName);
  if (!data) return 'not_found';
  const state = data.State && data.State.Status;
  if (state === 'running') return 'running';
  if (state === 'exited') return 'stopped';
  return state || 'unknown';
}

async function generateDockerfile(appPath, serviceType, detectedFrameworks, buildCommand, startCommand, containerPort) {
  const dockerfilePath = path.join(appPath, 'Dockerfile');
  const dockerignorePath = path.join(appPath, '.dockerignore');

  if (!fs.existsSync(dockerignorePath)) {
    fs.writeFileSync(dockerignorePath, DEFAULT_DOCKERIGNORE, 'utf8');
  }

  let frameworks = [];
  try {
    if (detectedFrameworks) {
      frameworks = typeof detectedFrameworks === 'string'
        ? JSON.parse(detectedFrameworks)
        : detectedFrameworks;
    }
  } catch {}

  const manifestReport = analyzeDependencyManifests(appPath);
  const hasPackageJson = manifestReport.hasPackageJson;
  const packageScripts = readPackageScripts(appPath);
  const hasBuildScript = typeof packageScripts.build === 'string' && packageScripts.build.trim().length > 0;
  const installPlan = getNodeInstallPlan(appPath);
  const pythonInstallCommand = getPythonDependencyInstallCommand(appPath);
  const resolvedContainerPort = containerPort || config.defaultContainerPort;
  const isStatic = shouldUseStaticContainer(serviceType, frameworks);

  if (!hasPackageJson && !isStatic) {
    throw new Error(
      'No package.json found in this repository. ReHoster requires a package.json to build Node.js apps. ' +
      'Add a package.json, or change the service type to "static" if this is a plain static site.'
    );
  }

  // For static apps without package.json, avoid all npm steps.
  // Only pass the build command through if the user explicitly set something non-npm.
  const isNpmDefaultCmd = (cmd) => !cmd || /^\s*(npm (install|ci|run build)|yarn( build)?)\s*/.test(cmd);
  const initialBuildCommand = buildCommand && buildCommand.trim().length > 0
    ? buildCommand
    : (isStatic && hasPackageJson ? 'npm run build' : null);
  const resolvedBuildCommand = normalizeBuildCommandForScripts(initialBuildCommand, hasBuildScript);
  const resolvedStartCommand = startCommand && startCommand.trim().length > 0
    ? startCommand
    : 'npm start';

  const content = (!hasPackageJson && isStatic)
    ? buildPureStaticDockerfile({
        buildCommand: isNpmDefaultCmd(resolvedBuildCommand) ? null : resolvedBuildCommand,
        containerPort: resolvedContainerPort,
      })
    : isStatic
      ? buildStaticDockerfile({ setupCommand: installPlan.setupCommand, installCommand: installPlan.installCommand, buildCommand: resolvedBuildCommand, containerPort: resolvedContainerPort })
      : buildNodeDockerfile({
          setupCommand: installPlan.setupCommand,
          installCommand: installPlan.installCommand,
          productionInstallCommand: installPlan.productionInstallCommand,
          pythonInstallCommand,
          buildCommand: resolvedBuildCommand,
          startCommand: resolvedStartCommand,
          containerPort: resolvedContainerPort,
        });

  let shouldWrite = !fs.existsSync(dockerfilePath);
  if (!shouldWrite) {
    const existing = fs.readFileSync(dockerfilePath, 'utf8');
    shouldWrite = existing.includes(GENERATED_DOCKERFILE_MARKER) || isLegacyGeneratedDockerfile(existing);
  }

  if (shouldWrite) {
    fs.writeFileSync(dockerfilePath, content, 'utf8');
  }
}

async function removeImage(imageName) {
  return runCommand(DOCKER_CMD, ['rmi', '-f', imageName], { timeout: 30000 });
}

module.exports = {
  isDockerAvailable,
  attemptDockerAutoRepair,
  analyzeDependencyManifests,
  getDockerAvailabilityDetails,
  getDockerCommandInfo,
  buildImage,
  runContainer,
  stopContainer,
  startContainer,
  restartContainer,
  removeContainer,
  getLogs,
  inspect,
  getContainerStatus,
  generateDockerfile,
  removeImage,
};
